### ISSUE TITLE
Get 404 error on console

### ISSUE THREAD

**Issue by lucianomlima** [fdaciuk/most-voted#2]
<img width="1281" alt="Captura de Tela 2019-04-09 às 23 24 32" src="https://user-images.githubusercontent.com/1580205/55847176-b9735280-5b1e-11e9-91dd-7512bdab8f10.png">

**Comment by fdaciuk** [comment]
Thanks @lucianomlima! Solved [here](https://github.com/fdaciuk/most-voted/commit/6996ffc3b93ceed3119cd6de90717fd826853aad) :)
